# Configurações gerais da aplicação
spring:
  application:
    name: ouvidoria
    description: Portal de Ouvidoria Simples
  
  # Configurações de validação
  validation:
    enabled: true
  
  # Configurações de timezone
  jackson:
    time-zone: America/Sao_Paulo
  
  # Configurações de CORS
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# Configurações do SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Configurações de encoding
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
