# Configurações do perfil de desenvolvimento
spring:
  profiles:
    active: dev
  
  # Configurações do banco MySQL 8.0
  datasource:
    url: jdbc:mysql://localhost:3306/ouvidoria_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  
  # Configurações JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  
  # Configurações Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    url: jdbc:mysql://localhost:3306/ouvidoria_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
    user: root
    password: root

# Configurações do servidor
server:
  port: 8080

# Configurações de logging
logging:
  level:
    com.cidadecidada.ouvidoria: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
